version: "3.3"
services:
  ocrmypdf:
    restart: always
    container_name: ocrmypdf
    user: 1000:1000
    image: jbarlow83/ocrmypdf
    volumes:
      - '$INPUT:/input'
      - '$OUTPUT:/output'
    environment:
      - OCR_OUTPUT_DIRECTORY_YEAR_MONTH=1
      - OCR_ON_SUCCESS_DELETE=1
      - OCR_DESKEW=1
      - PYTHONUNBUFFERED=1
    entrypoint: python3
    command: watcher.py
