---
version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM=$CONFIG
    volumes:
      - $CONFIG:/config
      - $TV:/tv
      - $MOVIES:/movies
    restart: unless-stopped
