version: '3.5'
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $SONARR_CONFIG:/config
      - $TV:/tv
      - $DOWNLOADS:/downloads
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - 9117:9117
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOWNLOADS:/downloads
      - $JACKETT_CONFIG:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=$TRANSMISSION_USER #optional
      - PASS=$TRANSMISSION_PASS #optional
    volumes:
      - $TRANSMISSION_CONFIG:/config
      - $DOWNLOADS:/downloads
      - $TRANSMISSION_WATCH:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=022 #optional
    volumes:
      - $RADARR_CONFIG:/config
      - $MOVIES:/movies
      - $DOWNLOADS:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
